--What is the most common room type in NYC Airbnb listings?
SELECT room_type, COUNT(*)
FROM room_types
GROUP BY 1

--What is the average price of a listing by room type?
SELECT room_type, AVG(price)
FROM room_types
JOIN prices
USING (listing_id)
GROUP BY 1

--Which borough has the highest average price per month?
SELECT borough, AVG(price_per_month)
FROM prices
GROUP BY 1
ORDER BY 2 DESC

--How many listings of each room type are in each borough?
SELECT borough, room_type, COUNT(*)
FROM prices
JOIN room_types
USING(listing_id)
GROUP BY 1, 2

--How many listings in each room type category have a price of over $500 per night?
SELECT room_type, COUNT(*)
FROM prices
JOIN room_types
USING(listing_id)
WHERE price>500
GROUP BY 1

--What is the distribution of listing prices by neighborhood?
SELECT borough, MIN(price), MAX(price), AVG(price)
FROM prices
GROUP BY 1

--What is the estimated amount of revenue generated by hosts in each borough?
SELECT borough, SUM(price*booked_days_365)  
FROM prices
JOIN reviews
USING (listing_id)
GROUP BY 1

--What is the average price per month for listings in each neighborhood?
SELECT neighbourhood, room_type, AVG(price_per_month)
FROM room_types
JOIN prices
USING (listing_id)
GROUP BY 1, 2

--How many listings have no reviews?
SELECT COUNT(*)-COUNT(last_review)
FROM reviews
FULL OUTER JOIN prices
USING (listing_id)

--How do the estimated book days correlate with the price of an Airbnb listing in New York City?
SELECT CORR(price, booked_days_365)
FROM reviews
JOIN prices
USING (listing_id)

--What is the average price per room type for listings that have at least 100 reviews and are available more than 200 days a year?
SELECT room_type, AVG(price)
FROM reviews
JOIN prices
USING (listing_id)
JOIN room_types
USING (listing_id)
WHERE number_of_reviews>100 AND availability_365>200
GROUP BY 1

--How many hosts have more than one listing, and what's the maximum number of listings by a single host name?
SELECT host_name, COUNT(*)
FROM reviews
GROUP BY 1
HAVING COUNT(*)>1
ORDER BY 2 DESC

--Determine the top 5 hosts who have the highest price_per_month for their listings, considering only hosts who have at least 10 listings.
SELECT host_name, MAX(price_per_month)
FROM prices
JOIN reviews
USING (listing_id)
WHERE host_name IN
            (SELECT host_name
            FROM reviews
            GROUP BY 1
            HAVING COUNT(*)>=10)
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

--Find the neighborhood(s) that have the highest variance in listing prices.
SELECT neighbourhood, var_samp(price)
FROM prices
GROUP BY 1
HAVING var_samp(price) IS NOT NULL
ORDER BY 2 DESC

--Calculate the average price_per_month for each neighborhood, taking into account only listings where the host has a minimum_nights value that is higher than the average minimum_nights value across all listings.
SELECT neighbourhood, AVG(price_per_month)
FROM prices
WHERE listing_id IN
        (SELECT listing_id
        FROM reviews
        WHERE minimum_nights>
                (SELECT AVG(minimum_nights)
                FROM reviews))
GROUP BY 1
ORDER BY 2 DESC

--Mean and standard deviation of the neighborhoods booked days
SELECT AVG(mean), STDDEV_SAMP(mean) 
FROM (
        SELECT neighbourhood, AVG(booked_days_365) as mean
        FROM prices
        JOIN reviews
        USING(listing_id)
        GROUP BY 1)
        AS t1